export const getDefaultEditorOptions = (
  value: string,
  language: string,
  theme: string,
  readOnly: boolean,
  customOptions: any = {},
) => ({
  value,
  language,
  theme,
  readOnly,
  automaticLayout: true,
  selectOnLineNumbers: true,
  roundedSelection: false,
  cursorStyle: "line",
  fontSize: 14,
  lineNumbers: "on",
  glyphMargin: true,
  folding: true,
  tabIndex: 0,

  // Auto-completion and IntelliSense
  autoClosingBrackets: "always",
  autoClosingQuotes: "always",
  autoSurround: "languageDefined",
  bracketPairColorization: { enabled: true },
  guides: {
    bracketPairs: true,
    bracketPairsHorizontal: true,
    highlightActiveBracketPair: true,
    indentation: true,
  },
  suggest: {
    enableSnippets: true,
    showKeywords: true,
    showSnippets: true,
    showFunctions: true,
    showConstructors: true,
    showFields: true,
    showVariables: true,
    showClasses: true,
    showModules: true,
    showProperties: true,
    showMethods: true,
  },
  quickSuggestions: {
    other: true,
    comments: false,
    strings: false,
  },
  parameterHints: { enabled: true },
  wordBasedSuggestions: true,
  semanticHighlighting: { enabled: true },
  occurrencesHighlight: true,
  selectionHighlight: true,
  codeLens: true,
  colorDecorators: true,

  // Formatting
  insertSpaces: true,
  tabSize: 2,
  detectIndentation: true,
  trimAutoWhitespace: true,

  ...customOptions,
});
